version: '3.9'
services:
  user:
    build: ./users
    container_name: mc_user
    restart: always
    hostname: users
    env_file:
      - ./.env
    ports:
     - "4001:4001"
    networks:
      - backend
    links:
      - shard1svr1
      - shard1svr2
      - shard1svr3
networks:
  backend:
    driver: bridge
